// <auto-generated />
using System;
using DoorsWeb.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoorsWeb.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260610220258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessLevelUser", b =>
                {
                    b.Property<Guid>("AccessLevelsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("AccessLevelsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AccessLevelUser");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AccessCalendar");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessCalendarElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessCalendarId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccessCalendarId");

                    b.ToTable("AccessCalendarElement");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TimeZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TimeZoneId");

                    b.ToTable("AccessLevel");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessLevelElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessTimeZone")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("AccessTimeZone");

                    b.HasIndex("DoorId");

                    b.ToTable("AccessLevelElement");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessTimeZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AccessTimeZone");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessTimeZoneElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessTimeZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccessTimeZoneId");

                    b.HasIndex("CalendarId");

                    b.ToTable("AccessTimeZoneElement");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanEditAdmins")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEditDoors")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEditUsers")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a22d0dac-9476-4bc9-a564-77c36963d85e"),
                            CanEditAdmins = true,
                            CanEditDoors = true,
                            CanEditUsers = true,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$KaHdki2KyqrcPv9inpMeDuisvjAklAdKJeRqJuam.xpCRgjl00CUS",
                            Username = "super"
                        });
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.DoorHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ControllerId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("IPAddressBytes")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId")
                        .IsUnique();

                    b.ToTable("DoorHeader");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.DoorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRelockEnable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DoorHeader")
                        .HasColumnType("uuid");

                    b.Property<int?>("Keypad_AccessCode")
                        .HasColumnType("integer");

                    b.Property<bool>("Keypad_StarModeEnable")
                        .HasColumnType("boolean");

                    b.Property<byte>("Keypad_VCardLength")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<byte>("LockDriveMode")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<byte>("PDO_Alarm_Time")
                        .HasColumnType("smallint");

                    b.Property<byte>("ReaderA_Brightness")
                        .HasColumnType("smallint");

                    b.Property<byte>("ReaderA_MFA_Sequence")
                        .HasColumnType("smallint");

                    b.Property<string>("ReaderA_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("ReaderA_TechId")
                        .HasColumnType("smallint");

                    b.Property<byte>("ReaderA_Volume")
                        .HasColumnType("smallint");

                    b.Property<byte>("ReaderB_Brightness")
                        .HasColumnType("smallint");

                    b.Property<byte>("ReaderB_MFA_Sequence")
                        .HasColumnType("smallint");

                    b.Property<string>("ReaderB_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("ReaderB_TechId")
                        .HasColumnType("smallint");

                    b.Property<byte>("ReaderB_Volume")
                        .HasColumnType("smallint");

                    b.Property<byte>("RelayA_Delay")
                        .HasColumnType("smallint");

                    b.Property<bool>("RelayA_TZOverideEnable")
                        .HasColumnType("boolean");

                    b.Property<byte>("RelayA_Time")
                        .HasColumnType("smallint");

                    b.Property<byte>("RelayB_Delay")
                        .HasColumnType("smallint");

                    b.Property<byte>("RelayB_Mode")
                        .HasColumnType("smallint");

                    b.Property<byte>("RelayB_Time")
                        .HasColumnType("smallint");

                    b.Property<TimeOnly>("ValidFrom")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("ValidTo")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("DoorSettings");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.DoorStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AlarmDoorForced")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlarmDuress")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlarmFire")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlarmHacker")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlarmIntruder")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlarmObstruction")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DoorHeader")
                        .HasColumnType("uuid");

                    b.Property<bool>("DoorPosition")
                        .HasColumnType("boolean");

                    b.Property<bool>("Interlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("RelayA")
                        .HasColumnType("boolean");

                    b.Property<bool>("RelayB")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequestToExit")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoStageRelease")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DoorStatus");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DoorId")
                        .HasColumnType("uuid");

                    b.Property<short>("EventTypeId")
                        .HasColumnType("smallint");

                    b.Property<byte?>("ReaderId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.EventType", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventType");

                    b.HasData(
                        new
                        {
                            Id = (short)0,
                            Name = "Card OK"
                        },
                        new
                        {
                            Id = (short)1,
                            Name = "Invalid Card"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Card and PIN OK"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Invalid PIN"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "Card Otl"
                        },
                        new
                        {
                            Id = (short)5,
                            Name = "Card Expired"
                        },
                        new
                        {
                            Id = (short)6,
                            Name = "Unknown Card"
                        },
                        new
                        {
                            Id = (short)7,
                            Name = "Anti Pass Back Failure"
                        },
                        new
                        {
                            Id = (short)8,
                            Name = "Request to Exit"
                        },
                        new
                        {
                            Id = (short)9,
                            Name = "Door Stuck Open"
                        },
                        new
                        {
                            Id = (short)10,
                            Name = "Fire Alarm"
                        },
                        new
                        {
                            Id = (short)11,
                            Name = "Fire Reset"
                        },
                        new
                        {
                            Id = (short)12,
                            Name = "Fire Fault"
                        },
                        new
                        {
                            Id = (short)13,
                            Name = "Intruder"
                        },
                        new
                        {
                            Id = (short)14,
                            Name = "Intruder Reset"
                        },
                        new
                        {
                            Id = (short)15,
                            Name = "Intruder Fault"
                        },
                        new
                        {
                            Id = (short)16,
                            Name = "Door Forced"
                        },
                        new
                        {
                            Id = (short)17,
                            Name = "Door Release by PC"
                        },
                        new
                        {
                            Id = (short)18,
                            Name = "Door Pc Close"
                        },
                        new
                        {
                            Id = (short)19,
                            Name = "Door Pc Open"
                        },
                        new
                        {
                            Id = (short)20,
                            Name = "Tz Door Open"
                        },
                        new
                        {
                            Id = (short)21,
                            Name = "Tz Door Close"
                        },
                        new
                        {
                            Id = (short)22,
                            Name = "Powered Down"
                        },
                        new
                        {
                            Id = (short)23,
                            Name = "Powered Up"
                        },
                        new
                        {
                            Id = (short)24,
                            Name = "Door Pc Release B"
                        },
                        new
                        {
                            Id = (short)25,
                            Name = "Door Pc Close B"
                        },
                        new
                        {
                            Id = (short)26,
                            Name = "Door Pc Open B"
                        },
                        new
                        {
                            Id = (short)27,
                            Name = "Tz Door Open B"
                        },
                        new
                        {
                            Id = (short)28,
                            Name = "Tz Door Close B"
                        },
                        new
                        {
                            Id = (short)29,
                            Name = "Invalid Code"
                        },
                        new
                        {
                            Id = (short)30,
                            Name = "Code Ok"
                        },
                        new
                        {
                            Id = (short)31,
                            Name = "Premature Card"
                        },
                        new
                        {
                            Id = (short)32,
                            Name = "Supply Low Volts"
                        },
                        new
                        {
                            Id = (short)33,
                            Name = "Supply High Volts"
                        },
                        new
                        {
                            Id = (short)34,
                            Name = "Code Duress"
                        },
                        new
                        {
                            Id = (short)35,
                            Name = "Hacker"
                        },
                        new
                        {
                            Id = (short)36,
                            Name = "Menu Engineer"
                        },
                        new
                        {
                            Id = (short)37,
                            Name = "Menu User"
                        },
                        new
                        {
                            Id = (short)38,
                            Name = "Random Search"
                        },
                        new
                        {
                            Id = (short)39,
                            Name = "Reader Error"
                        },
                        new
                        {
                            Id = (short)46,
                            Name = "Card 4 Pin"
                        },
                        new
                        {
                            Id = (short)47,
                            Name = "Pin Timeout"
                        },
                        new
                        {
                            Id = (short)48,
                            Name = "Card 4 Code"
                        },
                        new
                        {
                            Id = (short)49,
                            Name = "Transaction Timeout"
                        },
                        new
                        {
                            Id = (short)50,
                            Name = "Card Code Ok"
                        },
                        new
                        {
                            Id = (short)54,
                            Name = "Interlocked"
                        },
                        new
                        {
                            Id = (short)55,
                            Name = "Bio Unknown"
                        },
                        new
                        {
                            Id = (short)56,
                            Name = "Bio Aborted"
                        },
                        new
                        {
                            Id = (short)57,
                            Name = "Bio Con Rx Tmp Err"
                        },
                        new
                        {
                            Id = (short)58,
                            Name = "Bio Invalid"
                        },
                        new
                        {
                            Id = (short)59,
                            Name = "Bio Timeout"
                        },
                        new
                        {
                            Id = (short)60,
                            Name = "Bio Duplicated"
                        },
                        new
                        {
                            Id = (short)61,
                            Name = "Bio Rdr Tx Tmp Err"
                        },
                        new
                        {
                            Id = (short)62,
                            Name = "Sequence Err"
                        },
                        new
                        {
                            Id = (short)63,
                            Name = "Seq Ok"
                        },
                        new
                        {
                            Id = (short)64,
                            Name = "No Bio Template"
                        },
                        new
                        {
                            Id = (short)65,
                            Name = "Bio Template List"
                        },
                        new
                        {
                            Id = (short)66,
                            Name = "Bio Rdr Rx Tmp Err"
                        },
                        new
                        {
                            Id = (short)67,
                            Name = "Bio Template Updated"
                        },
                        new
                        {
                            Id = (short)68,
                            Name = "Bio Template Deleted"
                        },
                        new
                        {
                            Id = (short)69,
                            Name = "Bio Duress"
                        },
                        new
                        {
                            Id = (short)70,
                            Name = "Multi Factor Over Ride Tz Open"
                        },
                        new
                        {
                            Id = (short)71,
                            Name = "Multi Factor Over Ride Tz Close"
                        },
                        new
                        {
                            Id = (short)73,
                            Name = "Telekey Low Battery"
                        },
                        new
                        {
                            Id = (short)74,
                            Name = "Call Button"
                        },
                        new
                        {
                            Id = (short)200,
                            Name = "Key Beep"
                        },
                        new
                        {
                            Id = (short)201,
                            Name = "Key Nokey"
                        },
                        new
                        {
                            Id = (short)202,
                            Name = "Starkey Beep"
                        },
                        new
                        {
                            Id = (short)203,
                            Name = "Bio Start Enrol"
                        },
                        new
                        {
                            Id = (short)204,
                            Name = "Admin Id Ok"
                        });
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("AccessLevelUser", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.AccessLevel", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWeb.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessCalendarElement", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.AccessCalendar", null)
                        .WithMany("Elements")
                        .HasForeignKey("AccessCalendarId");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessLevel", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.AccessTimeZone", "TimeZone")
                        .WithMany()
                        .HasForeignKey("TimeZoneId");

                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessLevelElement", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.AccessLevel", "AccessLevel")
                        .WithMany("Elements")
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWeb.Shared.Models.AccessTimeZone", "TimeZone")
                        .WithMany()
                        .HasForeignKey("AccessTimeZone");

                    b.HasOne("DoorsWeb.Shared.Models.DoorHeader", "DoorHeader")
                        .WithMany("ALElements")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");

                    b.Navigation("DoorHeader");

                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessTimeZone", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.AccessCalendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessTimeZoneElement", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.AccessTimeZone", null)
                        .WithMany("Elements")
                        .HasForeignKey("AccessTimeZoneId");

                    b.HasOne("DoorsWeb.Shared.Models.AccessCalendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.DoorSettings", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.DoorHeader", "Header")
                        .WithOne("Settings")
                        .HasForeignKey("DoorsWeb.Shared.Models.DoorSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.DoorStatus", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.DoorHeader", "Header")
                        .WithOne("Status")
                        .HasForeignKey("DoorsWeb.Shared.Models.DoorStatus", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.Event", b =>
                {
                    b.HasOne("DoorsWeb.Shared.Models.DoorHeader", "DoorHeader")
                        .WithMany()
                        .HasForeignKey("DoorId");

                    b.HasOne("DoorsWeb.Shared.Models.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWeb.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("DoorHeader");

                    b.Navigation("EventType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessCalendar", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessLevel", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.AccessTimeZone", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("DoorsWeb.Shared.Models.DoorHeader", b =>
                {
                    b.Navigation("ALElements");

                    b.Navigation("Settings");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
