using DoorsWeb.API.Services.Interfaces;
using DoorsWeb.Shared.Entities;

namespace DoorsWeb.API.Services
{
    public class UsersService : IUsersService
    {
        // Seeded default for new accounts left without a password (matches AuthService).
        private const string DefaultPassword = "654321";

        private readonly DoorsEnterpriseContext _context;
        private readonly IPwHashService _pwHash;

        public UsersService(DoorsEnterpriseContext context, IPwHashService pwHash)
        {
            _context = context;
            _pwHash = pwHash;
        }

        public async Task<List<Users>> GetAll()
        {
            var users = await _context.Users.AsNoTracking().ToListAsync();
            // Never expose password hashes to the client.
            foreach (var u in users) u.Password = string.Empty;
            return users;
        }

        public async Task<Users?> GetById(int id)
        {
            var user = await _context.Users.AsNoTracking().FirstOrDefaultAsync(u => u.Code == id);
            if (user is not null) user.Password = string.Empty;
            return user;
        }

        public async Task<List<Users>> Create(Users entity)
        {
            entity.Code = 0; // identity-generated by the database
            var raw = string.IsNullOrEmpty(entity.Password) ? DefaultPassword : entity.Password;
            entity.Password = _pwHash.Hash(raw);
            _context.Users.Add(entity);
            await _context.SaveChangesAsync();
            return await GetAll();
        }

        public async Task<List<Users>?> Update(int id, Users entity)
        {
            var existing = await _context.Users.FirstOrDefaultAsync(u => u.Code == id);
            if (existing is null) return null;

            existing.Description = entity.Description;
            existing.Administrator = entity.Administrator;
            // An empty password means "leave unchanged"; otherwise store the new one hashed.
            if (!string.IsNullOrEmpty(entity.Password))
                existing.Password = _pwHash.Hash(entity.Password);

            await _context.SaveChangesAsync();
            return await GetAll();
        }

        public async Task<List<Users>?> Delete(int id)
        {
            var existing = await _context.Users.FirstOrDefaultAsync(u => u.Code == id);
            if (existing is null) return null;
            _context.Users.Remove(existing);
            await _context.SaveChangesAsync();
            return await GetAll();
        }
    }
}
