using DoorsWeb.API.Services.Interfaces;
using DoorsWeb.Shared.DTO;
using DoorsWeb.Shared.Entities;

namespace DoorsWeb.API.Services
{
    public class UsersService : IUsersService
    {
        // Seeded default for new accounts left without a password (matches AuthService).
        private const string DefaultPassword = "654321";

        private readonly DoorsEnterpriseContext _context;
        private readonly IPwHashService _pwHash;
        private readonly IAuditService _audit;
        private readonly IPasswordPolicyService _passwordPolicy;

        public UsersService(DoorsEnterpriseContext context, IPwHashService pwHash, IAuditService audit, IPasswordPolicyService passwordPolicy)
        {
            _context = context;
            _pwHash = pwHash;
            _audit = audit;
            _passwordPolicy = passwordPolicy;
        }

        public async Task<List<Users>> GetAll()
        {
            var users = await _context.Users.AsNoTracking().ToListAsync();
            // Never expose password hashes to the client.
            foreach (var u in users) u.Password = string.Empty;
            return users;
        }

        public async Task<Users?> GetById(int id)
        {
            var user = await _context.Users.AsNoTracking().FirstOrDefaultAsync(u => u.Code == id);
            if (user is not null) user.Password = string.Empty;
            return user;
        }

        public async Task<List<Users>> Create(Users entity)
        {
            entity.Code = 0; // identity-generated by the database
            // A blank password means "seed the default" (the operator is forced to change it on first
            // login), so it is intentionally exempt from the policy. Any operator-supplied password is
            // enforced: 12-char minimum + not on the breached/common list (400 from the controller).
            if (!string.IsNullOrEmpty(entity.Password))
            {
                var validation = _passwordPolicy.Validate(entity.Password);
                if (!validation.IsValid)
                    throw new PasswordPolicyException(validation.Error!);
            }
            var raw = string.IsNullOrEmpty(entity.Password) ? DefaultPassword : entity.Password;
            entity.Password = _pwHash.Hash(raw);
            _context.Users.Add(entity);
            await _context.SaveChangesAsync();
            await _audit.LogAsync(AuditAction.Create, "User", entity.Code.ToString(), entity.Description);
            return await GetAll();
        }

        public async Task<List<Users>?> Update(int id, Users entity)
        {
            var existing = await _context.Users.FirstOrDefaultAsync(u => u.Code == id);
            if (existing is null) return null;

            // Last-Super protection: never let the only remaining Super be demoted, or the system
            // would have no one able to manage users. Surfaced as 409 by the controller.
            if (existing.Administrator && !entity.Administrator && await IsLastSuper(existing.Code))
                throw new InvalidOperationException(
                    "At least one Super user must remain. Promote another user to Super before removing this one's Super status.");

            existing.Description = entity.Description;
            existing.Administrator = entity.Administrator;
            existing.CardManagerAccess = entity.CardManagerAccess;
            existing.SiteSettingsAccess = entity.SiteSettingsAccess;
            existing.UserSettingsAccess = entity.UserSettingsAccess;
            existing.ReportsAccess = entity.ReportsAccess;
            // An empty password means "leave unchanged"; otherwise enforce the policy (12-char minimum
            // + not breached/common, surfaced as 400) and store the new one hashed.
            if (!string.IsNullOrEmpty(entity.Password))
            {
                var validation = _passwordPolicy.Validate(entity.Password);
                if (!validation.IsValid)
                    throw new PasswordPolicyException(validation.Error!);
                existing.Password = _pwHash.Hash(entity.Password);
            }

            await _context.SaveChangesAsync();
            await _audit.LogAsync(AuditAction.Update, "User", id.ToString(), existing.Description);
            return await GetAll();
        }

        public async Task<List<Users>?> Delete(int id)
        {
            var existing = await _context.Users.FirstOrDefaultAsync(u => u.Code == id);
            if (existing is null) return null;

            // Last-Super protection: block deleting the only remaining Super (409 from controller).
            if (existing.Administrator && await IsLastSuper(existing.Code))
                throw new InvalidOperationException(
                    "At least one Super user must remain. Promote another user to Super before deleting this one.");

            _context.Users.Remove(existing);
            await _context.SaveChangesAsync();
            await _audit.LogAsync(AuditAction.Delete, "User", id.ToString(), existing.Description);
            return await GetAll();
        }

        // True when the given user is the only Super left (no other user has Administrator set).
        private async Task<bool> IsLastSuper(int code) =>
            !await _context.Users.AnyAsync(u => u.Administrator && u.Code != code);
    }
}
